
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_COLCHETES ATRIBUICAO CONVERSAO_RESISTOR CONVERSAO_VALOR COR FECHA_COLCHETES FIM INICIO MOSTRAR PARALELO PONTO RESISTOR SERIE TERMINADOR_LINHA VALOR VALOR_RESISTOR VARIAVEL VIRGULAprograma : INICIO operacoes FIM\n        operacao : declarando \n                  | definicaoValor\n                  | mostrar\n    \n        operacoes : operacao \n    \n        operacoes : operacoes operacao \n    \n        tipo : RESISTOR \n             | VALOR_RESISTOR\n    \n        declarando : tipo VARIAVEL TERMINADOR_LINHA\n    \n        definicaoValor : VARIAVEL ATRIBUICAO VALOR TERMINADOR_LINHA\n    \n        mostrar : MOSTRAR ABRE_COLCHETES VARIAVEL FECHA_COLCHETES TERMINADOR_LINHA\n    '
    
_lr_action_items = {'INICIO':([0,],[2,]),'$end':([1,13,],[0,-1,]),'VARIAVEL':([2,3,4,5,6,7,8,11,12,14,17,18,21,23,],[9,9,-5,-2,-3,-4,15,-7,-8,-6,20,-9,-10,-11,]),'MOSTRAR':([2,3,4,5,6,7,14,18,21,23,],[10,10,-5,-2,-3,-4,-6,-9,-10,-11,]),'RESISTOR':([2,3,4,5,6,7,14,18,21,23,],[11,11,-5,-2,-3,-4,-6,-9,-10,-11,]),'VALOR_RESISTOR':([2,3,4,5,6,7,14,18,21,23,],[12,12,-5,-2,-3,-4,-6,-9,-10,-11,]),'FIM':([3,4,5,6,7,14,18,21,23,],[13,-5,-2,-3,-4,-6,-9,-10,-11,]),'ATRIBUICAO':([9,],[16,]),'ABRE_COLCHETES':([10,],[17,]),'TERMINADOR_LINHA':([15,19,22,],[18,21,23,]),'VALOR':([16,],[19,]),'FECHA_COLCHETES':([20,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'operacoes':([2,],[3,]),'operacao':([2,3,],[4,14,]),'declarando':([2,3,],[5,5,]),'definicaoValor':([2,3,],[6,6,]),'mostrar':([2,3,],[7,7,]),'tipo':([2,3,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> INICIO operacoes FIM','programa',3,'p_main','colorOhm_yacc.py',16),
  ('operacao -> declarando','operacao',1,'p_operacao','colorOhm_yacc.py',23),
  ('operacao -> definicaoValor','operacao',1,'p_operacao','colorOhm_yacc.py',24),
  ('operacao -> mostrar','operacao',1,'p_operacao','colorOhm_yacc.py',25),
  ('operacoes -> operacao','operacoes',1,'p_operacao_unica','colorOhm_yacc.py',31),
  ('operacoes -> operacoes operacao','operacoes',2,'p_operacoes','colorOhm_yacc.py',37),
  ('tipo -> RESISTOR','tipo',1,'p_tipo','colorOhm_yacc.py',43),
  ('tipo -> VALOR_RESISTOR','tipo',1,'p_tipo','colorOhm_yacc.py',44),
  ('declarando -> tipo VARIAVEL TERMINADOR_LINHA','declarando',3,'p_declarando','colorOhm_yacc.py',50),
  ('definicaoValor -> VARIAVEL ATRIBUICAO VALOR TERMINADOR_LINHA','definicaoValor',4,'p_definicaoValor','colorOhm_yacc.py',58),
  ('mostrar -> MOSTRAR ABRE_COLCHETES VARIAVEL FECHA_COLCHETES TERMINADOR_LINHA','mostrar',5,'p_mostrar','colorOhm_yacc.py',67),
]
